### ISSUE TITLE
Chown breaks some systems

### ISSUE THREAD

**Issue by LaneaLucy** [Opendigitalradio/dab-scripts#15]
https://github.com/Opendigitalradio/dab-scripts/blob/babedcf10802f2a9fe2629d9e61d24f67eaaffa9/install/mmbtools-get#L317

I installed this in a distrobox container on a steam deck with default user "deck" as odr user. 
inside the container, the deck user home directory is mapped to the real home directory outside the container, because on the steam deck, the home folder is the only partition/folder that survives a system update, therefore I must use it. 
But by the chown in the line mentioned above, everything inside the home directory will be chown'd by the odr user, which would break the host system, if I didn't used the host default user "deck" as odr user. 
but in doing so, because the files of the container lay inside the home directory too, it's chown every file of the container too, which includes the sudo binary, which breaks it with error message "[Error]sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set"
And this brakes the container.

So my idea would to be just chown the folders needed, "DIR_CONFIG" and "DIR_MMB" recursive. That would prevent to break any installation, where there can't add any users and therefore need to use the default user.

P.s. thx to https://github.com/89luca89/distrobox/issues/721#issuecomment-1522879848
To figure this out

**Comment by colisee** [comment]
Hi @LaneaLucy,

Thank you very much for having investigated the issue and for the 3 pull requests:
- PR #17: I am OK with it
- PR #16 and PR #18: I need to check them

Please note that your pull requests must point to the `next` branch. Is there a way for you to re-issue them against `next` ? If not, then I will make the changes on your behalf.

**Comment by LaneaLucy** [comment]
> * PR [Update ODR-misc.conf #16](https://github.com/Opendigitalradio/dab-scripts/pull/16): I am OK. Could you tell me more about the statement `stopsignal=INT` ?

This makes dabmod close the SDR connection. Without, my hackrf is stuck in tx. With it, it's like you press ctrl + c so dabmod can do its exit routines 


> * PR [make paths more safe #18](https://github.com/Opendigitalradio/dab-scripts/pull/18): I am OK with moving the directory `config` inside `ODR-mmbTools`, but not sure about the changes to the **sed** statements...

This makes changing the hard coded path's to the paths in the path variables. Without it, everything gets installed with the changed paths, but the supervisor config still has the hard coded path's in it and therefore, the configs and everything don't get found.


> Please note that your pull requests must point to the `next` branch. Is there a way for you to re-issue them against `next` ? If not, then I will make the changes on your behalf.

I have no idea, how to do it. But when you can do it, do it. If you need help with conflicts, ask me and I can help you

**Comment by colisee** [comment]
Thank you @LaneaLucy for your proposals and explanations that greatly helped me.

Regarding dab-scripts, I implemented the changes in the `next` branch.
Could you kindly test this branch by:
1. Cloning the `next` branch:
```
git clone --branch next https://github.com/opendigitalradio/dab-scripts.git
```
2. Installing the software (you can choose the branch of your choice)
```
# Install the stable version of odr-mmbTools
sudo bash dab-scripts/install/mmbtools-get --branch master install

# Or install the development version of odr-mmbTools
sudo bash dab-scripts/install/mmbtools-get --branch next install
```

Kind regards.

**Comment by LaneaLucy** [comment]
I will check the changes an test them this weekend

**Comment by LaneaLucy** [comment]
Commit cc4e312 only changes hardcoded paths to different hardcoded paths. This is still bad...
The way I did it, you can freely configure the paths inside "mmbtools-get.conf".
With the hardcoded paths, "mmbtools-get.conf"  makes no sense, because changing it, brakes the software configuration. Hardcoded paths are not good...

**Comment by colisee** [comment]
OK, I will completely remove the path hard-codings that are reminiscent of my first installations on a raspberry pi.

**Comment by colisee** [comment]
Hi @LaneaLucy , could you check again the lat commit a828deb in the `next` branch?

**Comment by LaneaLucy** [comment]
Looks looks good at first sight. The only thing I still would change, is that the chown do both, the "DIR_MMB" and "DIR_CONFIG" in case someone wants to change the config dir independent.

But I will test it later, when I finally can borrow a dab radio

**Comment by colisee** [comment]
In the `next` branch, mmbtools-get does:
```
chown --recursive ${odr_user}:${odr_user} ${DIR_MMB}
```

Thus, if you would like some directories to be excluded from the chown, you would change the path inside the `mmbtools-get.conf` file. For instance, if you don't want to change the owner of the config folder, then you could change:
```
# From current path:
DIR_CONFIG=${DIR_MMB}/config

# To new path:
DIR_CONFIG=<whatever_path_outside_of_DIR_MMB>
```

**Comment by LaneaLucy** [comment]
I know. But what if someone for example want the config folder inside /etc/?
Then this path need chown to new user too. That's why I would chown both directory's separately to make sure, wherever they are inside of each or not, they both have right permissions.

**Comment by colisee** [comment]
Normally, files inside /etc belong to `root` 

At this stage, I prefer to keep the code in `next` as-is, knowing that the user can always make the final changes manually. Regardless, I believe that the code in `next` should fulfill your constraints on the steam deck, now; shouldn't it?

**Comment by LaneaLucy** [comment]
It's working for me right now
